name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.5'

      - name: Build for multiple platforms
        run: |
          GOOS=linux GOARCH=amd64 go build -o pesp-sat-linux-amd64 main.go commands.go
          GOOS=darwin GOARCH=amd64 go build -o pesp-sat-darwin-amd64 main.go commands.go
          GOOS=windows GOARCH=amd64 go build -o pesp-sat-windows-amd64.exe main.go commands.go

      - name: Create Release
        id: create_release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: elease ${{ github.ref }}
        permissions:
          packages: write
          contents: write

      - name: Upload Linux Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pesp-sat-linux-amd64
          asset_name: pesp-sat-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload macOS Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pesp-sat-darwin-amd64
          asset_name: pesp-sat-darwin-amd64
          asset_content_type: application/octet-stream

      - name: Upload Windows Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pesp-sat-windows-amd64.exe
          asset_name: pesp-sat-windows-amd64.exe
          asset_content_type: application/octet-stream