name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.5'

      - name: Build for multiple platforms
        run: |
          GOOS=linux GOARCH=amd64 go build -o pesp-sat-linux-amd64 ./cmd/pesp/...
          GOOS=darwin GOARCH=amd64 go build -o pesp-sat-darwin-amd64 ./cmd/pesp/...
          GOOS=windows GOARCH=amd64 go build -o pesp-sat-windows-amd64.exe ./cmd/pesp/...

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            pesp-sat-linux-amd64
            pesp-sat-darwin-amd64
            pesp-sat-windows-amd64.exe